# Generated by Django 3.0.8 on 2020-07-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.State')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.State')),
            ],
        ),
    ]
