# Generated by Django 3.0.8 on 2020-07-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='person.State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='county',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='person.Country'),
        ),
    ]
