# Generated by Django 3.0.8 on 2020-07-29 09:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200729_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondeatail',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
