# Generated by Django 3.0.8 on 2020-07-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
