# Generated by Django 3.0.8 on 2020-07-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200701_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
