# Generated by Django 3.0.8 on 2020-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200702_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.CharField(max_length=11),
        ),
    ]
