# Generated by Django 3.0.8 on 2020-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algebraAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answerIMG',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answerTXT',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
